# GENERATED by ./emacs.org
# DO NOT EDIT

{ pkgs, ... }:

{
  pkgs = [
    pkgs.emacs-lsp-booster
    pkgs.go
    pkgs.gopls
    pkgs.delve
    pkgs.gleam
    pkgs.beam28Packages.erlang
    pkgs.erlang-language-platform
    pkgs.nil
    pkgs.nixfmt
    pkgs.bash-language-server
    pkgs.guile
    pkgs.luajit
    pkgs.lua-language-server
    pkgs.zig
    pkgs.zls
    pkgs.hurl
    pkgs.ledger
  ];

  epkgs = epkgs: [
    epkgs.exec-path-from-shell
    epkgs.envrc
    epkgs.meow
    epkgs.evil
    epkgs.nerd-icons
    epkgs.ligature
    epkgs.doom-themes
    epkgs.doom-modeline
    epkgs.corfu
    epkgs.vertico
    epkgs.marginalia
    epkgs.nerd-icons-completion
    epkgs.golden-ratio
    epkgs.focus
    epkgs.pulsar
    epkgs.spacious-padding
    epkgs.hide-mode-line
    epkgs.visual-fill-column
    epkgs.helpful
    epkgs.which-key
    epkgs.keycast
    epkgs.markdown-mode
    epkgs.otpp
    epkgs.harpoon
    epkgs.consult
    epkgs.orderless
    epkgs.cape
    epkgs.tempel
    epkgs.eglot-tempel
    epkgs.eglot-booster
    epkgs.eldoc-box
    epkgs.treesit-grammars.with-all-grammars
    # go-ts-mode is already emacs built-in major mode
    epkgs.gleam-ts-mode
    epkgs.erlang-ts
    epkgs.nix-ts-mode
    epkgs.geiser
    epkgs.geiser-guile
    # lua-ts-mode is already emacs built-in major mode
    epkgs.zig-mode
    epkgs.zig-ts-mode
    epkgs.org-modern
    (pkgs.emacsPackages.trivialBuild {
      pname = "org-modern-indent";
      version = "0.5.1";
      src = pkgs.fetchFromGitHub {
        owner = "jdtsmith";
        repo = "org-modern-indent";
        rev = "v0.5.1";
        sha256 = "sha256-st3338Jk9kZ5BLEPRJZhjqdncMpLoWNwp60ZwKEObyU=";
      };
    })
    epkgs.ox-hugo
    epkgs.org-tree-slide
    epkgs.org-tree-slide-pauses
    epkgs.org-roam
    epkgs.org-roam-ui
    epkgs.verb
    (pkgs.emacsPackages.trivialBuild {
      pname = "hurl-mode";
      version = "0.0.0";
      src = pkgs.fetchFromGitHub {
        owner = "JasZhe";
        repo = "hurl-mode";
        rev = "0753271bb4693924d3dcfa9d66a316086d7b7b72";
        sha256 = "sha256-56/XDXYG4pq3+liB9TDIISTlmN4xMGsic9jhrIacO5E=";
      };
    })
    epkgs.magit
    epkgs.blamer
    epkgs.diff-hl
    epkgs.avy
    epkgs.jwt
    epkgs.ledger-mode
  ];
}
